# Generated by Django 4.1.7 on 2023-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes_no',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_ip',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
